---
title: "week2 R md practice"
author: "Shibo"
date: '1/13/2020'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Big Section

## subsection

### sub-subection 

## Load packages

```{r, load_packages, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
```

## Practice dataset

work with the `mtcars` dataset.  
New line of text, after ending the line with 2 spaecs

```{r, look_at_mtcars}
mtcars %>% glimpse
class(mtcars$mpg)
mtcars$mpg 

'car and make are the row names for mtcars' 
mtcars
```


```{r, tibble_df}
class(mtcars)

#pipe mtcars to tible
mtcars %>%
  tbl_df %>% class 



#colon-colon operator access a specific function from a class
mtcars %>% 
  tbl_df() %>% 
  tibble::rownames_to_column('my_rowname') %>% #generate a chr column
  mutate(car_name = rownames(mtcars)) #mutate is a verb that creates a new column
```

Assign out actions to a new variable or object
```{r, create_b_dataset}
mtcars_b <- mtcars %>%
  tbl_df() %>%
  tibble::rowid_to_column() %>%
  tibble::rownames_to_column('my_rowname') %>%
  mutate(car_name = rownames(mtcars))

```

`select()` verb, `filter()`, desc, arrange, distinct, count and summarise verbs
```{r}
mtcars_b %>%
  dplyr::select(car_name, my_rowname, rowid) %>% 
  select(c(1, 3)) %>% 
  select(ends_with('e'))

mtcars_b %>%
  filter(mpg > 11 & disp > 000170.5)

mtcars_b %>%
  arrange(desc(mpg))

mtcars_b %>%
  distinct(cyl) %>%
  arrange(desc(cyl))

mtcars_b %>%
  group_by(cyl) %>%
  summarise(num_rows = n(), avg_mpg = mean(mpg)) #summarise the dataset based on the group_by performed




```
